# Generated by Django 5.1.5 on 2025-05-04 19:20

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("aiserv", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationconfig",
            name="sent_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="notificationconfig",
            name="expire_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]

