# Generated by Django 5.1.5 on 2025-05-04 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aiserv', '0002_auto_20250504_1920'),
    ]

    operations = [
    ]
