# Generated by Django 5.1.5 on 2025-06-11 19:15

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aiserv', '0003_auto_20250504_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiservuser',
            name='auth_token_access',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aiservuser',
            name='auth_token_refresh',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
    ]
