# Generated by Django 5.1.5 on 2025-06-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiserv', '0004_alter_aiservuser_auth_token_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiservuser',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
    ]
